app/routes.php
<?php

/*
|
|   Home Routes
|
 */

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('show', ['as' => 'show', 'uses' => 'HomeController@show']);

/*
|
|   Admin Routes
|*/

Route::get('login', ['as' => 'login', 'uses' => 'UserController@login_form']);
Route::post('admin/login/process', ['as' => 'login.process', 'uses' => 'UserController@login_process']);
Route::get('signup', ['as' => 'signup', 'uses' => 'UserController@create']);
Route::post('signup/process', ['as' => 'signup.process', 'uses' => 'UserController@store']);

Route::group(['before' => 'auth'], function () {
	Route::get('admin', ['as' => 'admin', 'uses' => 'AdminController@index']);
	Route::group(['before' => 'role'], function () {
		Route::resource('admin/user', 'UserController', ['except' => ['create', 'store']]);
		Route::get('admin/user/{user}/approve', ['as' => 'user.approve', 'uses' => 'UserController@approve']);
	});
	Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
	Route::get('admin/{user}/delete', ['as' => 'user.delete', 'uses' => 'UserController@destroy']);
	Route::get('post/{id}/delete', ['as' => 'post.delete', 'uses' => 'PostController@destroy']);
	Route::get('post/{id}/approve', ['as' => 'post.approve', 'uses' => 'PostController@approve']);
	Route::post('post/{id}/comment', ['as' => 'post.comment', 'uses' => 'PostController@comment']);
});
Route::resource('post', 'PostController');

app/views/pages/create_post.blade.php
@extends('layouts.admin_master')

@section('title') 

    Create Post

@stop

@section('content') 
   
    
    {{Form::open(['route' => 'post.store', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data'])}}
    
        <div class="col-md-10">
            <div class="form-group">
                <div class="col-sm-3 ">
                    <label for="post_title" class="control-label">Post Title</label>
                </div>
                <div class="col-sm-9">
                    {{Form::text('title', null ,['class' => 'form-control', 'id' => 'post_title'])}}
                    <span class="text-danger pull-right">{{$errors->first('title')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label for="post_content" class="control-label">Post Contents</label>
                </div>
                <div class="col-sm-9">
                    {{Form::textarea('content', null ,['class' => 'form-control', 'id' => 'post_content'])}}
                    <span class="text-danger pull-right">{{$errors->first('content')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label for="post_image" class="control-label">Post Image</label>
                </div>
                <div class="col-sm-9">
                    {{Form::file('attachment', ['id' => 'post_image'])}}
                    <span class="text-danger pull-right">{{$errors->first('attachment')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label class="control-label">Tags</label>
                </div>
                <div class="col-sm-9">
                    @foreach($tags as $tag)
                        <label>{{Form::checkbox('tags[]', $tag->id)}} {{$tag->name}}</label>
                    @endforeach
                    <span class="text-danger pull-right">{{$errors->first('tags')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12 text-right">
                    <input type="submit" value="Create Post" class="btn btn-info">
                </div>
            </div>
        </div>
    
    {{Form::close()}}
    
@stop

app/views/pages/create_user.blade.php
@extends('layouts.master')

@section('title')

    Create User

@stop()

@section('content')

        <div class="col-md-6 col-md-offset-3">
            {{Form::open(['route' => 'signup.process', 'class' => 'form-horizontal'])}}

                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="first_name" class="control-label">First Name</label>
                    </div>
                    <div class="col-sm-8">
                        {{Form::text('first_name', null ,['class' => 'form-control', 'id' => 'first_name'])}}
                        <span class="text-danger pull-right">{{$errors->first('first_name')}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="last_name" class="control-label">Last Name</label>
                    </div>
                    <div class="col-sm-8">
                        {{Form::text('last_name', null ,['class' => 'form-control', 'id' => 'last_name'])}}
                        <span class="text-danger pull-right">{{$errors->first('last_name')}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="username" class="control-label">Username</label>
                    </div>
                    <div class="col-sm-8">
                        {{Form::text('username', null ,['class' => 'form-control', 'id' => 'username'])}}
                        <span class="text-danger pull-right">{{$errors->first('username')}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="email" class="control-label">Email</label>
                    </div>
                    <div class="col-sm-8">
                        {{Form::email('email', null ,['class' => 'form-control', 'id' => 'email'])}}
                        <span class="text-danger pull-right">{{$errors->first('email')}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="role" class="control-label">Role</label>
                    </div>
                    <div class="col-sm-8">
                        <select name="role" class="form-control">
                            <option value="0">-- Select A Role --</option>
                            @foreach($roles as $role)
                                <option value="{{$role->id}}">{{$role->name}}</option>
                            @endforeach
                        </select>
                        <span class="text-danger pull-right">{{$errors->first('role')}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="password" class="control-label">Password</label>
                    </div>
                    <div class="col-sm-8">
                        {{Form::password('password' ,['class' => 'form-control', 'id' => 'password'])}}
                        <span class="text-danger pull-right">{{$errors->first('password')}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12 text-right">
                        <input type="submit" value="Create User Account" class="btn btn-info">
                    </div>
                </div>
            {{Form::close()}}

            <p>Already have an account? Please <a href="{{route('login')}}">Login</a> here...</p>

        </div>


@stop

app/views/pages/dashboard.blade.php
@extends('layouts.admin_master')


@section('title')
    Dashboard
@stop()


@section('content')

    <h4>Pending Posts</h4>
    
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Post Title</th>
                    <th>Post Content</th>
                    <th>Post Image</th>
                    <th>Post Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Est, amet?</td>
                    <td>Repellendus, aperiam.</td>
                    <td>Cumque, quibusdam?</td>
                    <td class="text-center">
                        <label class="label label-success">Approved</label>
                        <label class="label label-warning">Pending</label>
                    </td>
                    <td class="text-center">
                        <a href="" class="text-info" data-toggle="tooltip" data-placement="top" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
                        <a href="" class="text-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="glyphicon glyphicon-trash"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    
@stop()

app/views/pages/edit_post.blade.php
@extends('layouts.admin_master')

@section('title')

    Edit Post - {{$post->title}}

@stop

@section('content')


    {{Form::open(['route' => ['post.update', $post->id], 'class' => 'form-horizontal', 'method' => 'PUT', 'enctype' => 'multipart/form-data'])}}

        <div class="col-md-10">
            <div class="form-group">
                <div class="col-sm-3 ">
                    <label for="post_title" class="control-label">Post Title</label>
                </div>
                <div class="col-sm-9">
                    {{Form::text('title', $post->title ,['class' => 'form-control', 'id' => 'post_title'])}}
                    <span class="text-danger pull-right">{{$errors->first('title')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label for="post_content" class="control-label">Post Contents</label>
                </div>
                <div class="col-sm-9">
                    {{Form::textarea('content', $post->content ,['class' => 'form-control', 'id' => 'post_content'])}}
                    <span class="text-danger pull-right">{{$errors->first('content')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label for="post_image" class="control-label">Post Image</label>
                </div>
                <div class="col-sm-9">
                    {{Form::file('attachment', ['id' => 'post_image'])}}
                    <span class="text-danger pull-right">{{$errors->first('attachment')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label class="control-label">Tags</label>
                </div>
                <div class="col-sm-9">
                    @foreach($tags as $tag)
                        <label>{{Form::checkbox('tags[]', $tag->id)}} {{$tag->name}}</label>
                    @endforeach
                    <span class="text-danger pull-right">{{$errors->first('tags')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12 text-right">
                    <input type="submit" value="Update Post" class="btn btn-info">
                </div>
            </div>
        </div>

    {{Form::close()}}

@stop

app/views/pages/edit_user.blade.php
@extends('layouts.admin_master')

@section('title') 

    Edit User

@stop()

@section('content') 
    
    {{Form::open(['route' => ['admin.user.update', $user->id], 'class' => 'form-horizontal', 'method' => 'PUT'])}}
    
        <div class="col-md-8">
            <div class="form-group">
                <div class="col-sm-4">
                    <label for="first_name" class="control-label">First Name</label>
                </div>
                <div class="col-sm-8">
                    {{Form::text('first_name', $user->first_name ,['class' => 'form-control', 'id' => 'first_name'])}}
                    <span class="text-danger pull-right">{{$errors->first('first_name')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4">
                    <label for="last_name" class="control-label">Last Name</label>
                </div>
                <div class="col-sm-8">
                    {{Form::text('last_name', $user->last_name ,['class' => 'form-control', 'id' => 'last_name'])}}
                    <span class="text-danger pull-right">{{$errors->first('last_name')}}</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12 text-right">
                    <input type="submit" value="Update User Account" class="btn btn-info">
                </div>
            </div>
        </div>
    
    {{Form::close()}}
    
@stop

app/views/pages/home.blade.php
@extends('layouts.master')

@section('title') Home @stop()

@section('content') 

@if($posts)
    @foreach($posts as $post)
    
    <div class="row">
        <div class="col-sm-4">
            @if($post->attachment)
                <img src="{{asset("uploads/posts/$post->user_id/$post->attachment")}}" class="img-responsive img-thumbnail" alt="" />
            @endif
        </div>
        <div class="col-sm-8">
            <h4><a href="{{route('post.show', $post->id)}}">{{$post->title}}</a></h4>
            <i class="text-muted">On: {{$post->created_at}}, By: {{$post->user['last_name']}}</i>
            <p>
                {{str_limit($post->content, 500, '...')}}
            </p>
            {{ link_to(route('post.show', $post->id), 'Details') }}
            <ul class="list-inline">
                @foreach($post->tags as $tag)
                <li class="label label-info">{{$tag->name}}</li>
                @endforeach
            </ul>
        </div>
    </div>
    @endforeach
    
    {{$posts->links()}}
    
@endif

@stop()

app/views/pages/login.blade.php
@extends('layouts.master')

@section('title')

Login

@stop()

@section('content')

<div class="col-md-4 col-md-offset-4">

    @if($errors->first('login'))
        <div class="alert alert-danger">
            {{{$errors->first('login')}}}
        </div>
    @endif

    {{Form::open(['route' => 'login.process', 'class' => 'form-horizontal'])}}

    <div class="form-group">
        <div class="col-sm-4">
            <label for="username" class="control-label">Username</label>
        </div>
        <div class="col-sm-8">
            {{Form::text('username', null ,['class' => 'form-control', 'id' => 'username'])}}
            <span class="text-danger pull-right">{{$errors->first('username')}}</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-4">
            <label for="password" class="control-label">Password</label>
        </div>
        <div class="col-sm-8">
            {{Form::password('password' ,['class' => 'form-control', 'id' => 'password'])}}
            <span class="text-danger pull-right">{{$errors->first('password')}}</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12 text-right">
            <input type="submit" value="Login" class="btn btn-info">
        </div>
    </div>

    {{Form::close()}}

    <p>Don't have an account? <a href="{{route('signup')}}">Create Account</a></p>

</div>

@stop

app/views/pages/post_details.blade.php
@extends('layouts.master')

@section('title') {{$post->title}} @stop()

@section('content')

@if($post)
<div class="row">
    <div class="col-sm-12">
        @if($post->attachment)
        <img src="{{asset("uploads/posts/$post->user_id/$post->attachment")}}" class="img-responsive img-thumbnail" alt="" />
        @endif
    </div>


    <div class="col-sm-12">
        <h4><a href="{{route('post.show', $post->id)}}">{{$post->title}}</a></h4>
        <p>
            {{{$post->content}}}
        </p>

        <div class="col-sm-6">
            <h4>All Comments</h4>
            <ul class="list-unstyled">
                @foreach($post->comments as $comment)
                    <li>
                        <a href="#">{{$comment->user->username}}, <i>On: {{$comment->created_at}}</i></a>
                        <p>{{$comment->comment}}</p>
                    </li>
                @endforeach

            </ul>
        </div>
        <div class="col-sm-6">
            <h4>Comment</h4>
            {{Form::open(['route' => ['post.comment', $post->id]])}}
            {{Form::textarea('comment', null, ['class'=>'form-control', 'placeholder'=>'Your Comment', 'required' => true])}}
            <span class="text-danger">{{$errors->first()}}</span>
            {{Form::submit('Send', ['class'=>'btn btn-success pull-right'])}}
            {{Form::close()}}
        </div>
    </div>


</div>
@endif

@stop()

app/views/pages/posts.blade.php
@extends('layouts.admin_master')

@section('title')

All Posts

@stop


@section('content')


@if($posts)
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Content</th>
                <th>Image</th>
                <th>Status</th>
                @if(Auth::user()->isAdmin())
                    <th>Author</th>
                @endif
                <th>Tags</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($posts as $i => $post)
            <tr>
                <td>{{$i+1}}</td>
                <td>{{str_limit($post->title, 30, '...')}}</td>
                <td>{{str_limit($post->content, 100, '...')}}</td>
                <td class="text-center"><img width="60" class="img-responsive" src="{{asset("uploads/posts/$post->user_id/$post->attachment")}}" alt="" /></td>
                <td class="text-center">
                    @if($post->approved)
                    <label class="label label-success">Approved</label>
                    @else
                    <label class="label label-warning">Pending</label>
                    @endif
                </td>

                @if(Auth::user()->isAdmin())
                    <td>{{$post->user['last_name']}}</td>
                @endif

                <td>
                    @foreach($post->tags as $tag)
                    <label class="label label-default">{{$tag->name}}</label>
                    @endforeach
                </td>
                <td class="text-center">
                    @if(Auth::user()->isAdmin())
                        @if(!$post->approved)
                            <a href="{{route('post.approve', $post->id)}}" class="text-success" title="Approve"><i class="glyphicon glyphicon-check"></i></a>
                        @endif
                    @endif
                    <a href={{url("post/{$post->id}/edit")}} class="text-info"><i class="glyphicon glyphicon-edit"></i></a>
                    <a href="{{route('post.delete', $post->id)}}" class="text-danger"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
            @endforeach()
        </tbody>
    </table>
</div>
{{$posts->links()}}
@else()
<div class="alert alert-info">
    No Post found
</div>
@endif()

@stop

app/views/pages/user_list.blade.php
@extends('layouts.admin_master') @section('title') Users List @stop @section('content')


<h4>Users List</h4> @if($users)
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $i => $user)

            <tr>
                <td>{{$i+1}}</td>
                <td>{{$user->first_name.' '.$user->last_name}}</td>
                <td>{{$user->username}}</td>
                <td>{{$user->email}}</td>
                <td class="text-center">
                    @foreach ($user->roles as $role)
                        <label class="label label-<?php if ($role->name == 'Admin') {
                            echo 'success';
                        } elseif ($role->name == 'Author') {
                            echo 'warning';
                        }
                        ?>">{{$role->name}}</label>
                    @endforeach
                </td>
                <td class="text-center">
                    <label class="label label-{{($user->approved ? 'success' : 'warning')}}">{{($user->approved ? 'Approved' : 'Pending')}}</label>
                </td>
                <td class="text-center">
                    @if(!$user->approved)
                    <a class="text-success" href="{{route('user.approve', $user->id)}}" title="Approve">
                        <i class="glyphicon glyphicon-check"></i>
                    </a>
                    @endif
                    <a href={{url( "admin/user/{$user->username}/edit")}} class="text-info"><i class="glyphicon glyphicon-edit"></i></a>
                    <a href="{{route('user.delete', $user->id)}}" class="text-danger"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
            @endforeach()
        </tbody>
    </table>
    {{ $users->links() }}
</div>
@else()
<div class="alert alert-info">
    No User found
</div>
@endif() @stop